[package]
name = "neuralnet"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

[dependencies]
nalgebra="*"
rand="*"
lazy_static="*"
threadpool="*"
num="*"
itertools="*"

